public class MyPagingController {

    public String getPageSize() {
        return null;
    }


    public String getNextButtonDisabled() {
        return null;
    }


    public PageReference nextBtnClick() {
        return null;
    }


    public String getPreviousButtonEnabled() {
        return null;
    }


    public PageReference previousBtnClick() {
        return null;
    }


    public String getTotalPageNumber() {
        return null;
    }


    public String getPageNumber() {
        return null;
    }


    public String getAccounts() {
        return null;
    }


    public PageReference ViewData() {
        return null;
    }

}